apiVersion: v1
kind: Service
metadata:
  name: techchallenger-front
  namespace: fiap
  labels:
    app: techchallenger-front
spec:
  type: ClusterIP
  selector:
    app: techchallenger-front
  ports:
  - name: http
    port: 3001        # Porta exposta internamente no Cluster IP
    targetPort: 3000  # Porta do container (onde o frontend responde)
    protocol: TCP